-- +goose Up
-- +goose StatementBegin
-- Per-image alt text, optionally generated by the AI writing assist
-- on upload. Empty string means "no alt yet" — the
-- image picker falls back to the filename-stripped slug so templates
-- always have *some* text even before AI fills this in.
ALTER TABLE images ADD COLUMN alt_text TEXT NOT NULL DEFAULT '';
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
SELECT 1;
-- +goose StatementEnd
