package public

import (
	"errors"
	"net/http"
	"strconv"
	"strings"

	"github.com/serendipitynz/serenebach/internal/storage/repo"
)

// legacyCGI fronts the `/sb.cgi` URL emitted by SB3 in two distinct
// flavours:
//
//  1. Internal template URLs ({site_cgi}?mode=…&eid=…). These appear
//     inside SB3-generated HTML — comment forms, search actions,
//     cross-page navigation. Imported templates render the SB3 spelling
//     until they're rewritten, and live SB3 admins still produce them.
//
//  2. External permalinks (?eid=N / ?cid=N / ?month=YYYYMM, no `mode`
//     param). SB3's permalink() emits these for dynamic-only blogs;
//     external links and bookmarks landed on this shape.
//
// We don't run the old Perl dispatcher — we translate the request into
// the Go port's canonical URL and let chi route from there.
//
// Translations:
//
//	?eid=N (no mode)        → 301 /entry/{key}/    (legacy_id lookup)
//	?cid=N (no mode)        → 301 /category/{id}/  (legacy_id lookup)
//	?month=YYYYMM (no mode) → 301 /archive/YYYY/MM/
//	mode=entry&eid=N        → 301 /entry/{key}/    (legacy_id lookup)
//	mode=category&cid=N     → 301 /category/{id}/  (legacy_id lookup)
//	mode=archive&cond=YYYYMM[DD]
//	                        → 301 /archive/YYYY[/MM]/
//	mode=user&pid=N         → 301 /profile/N/      (id passthrough; user
//	                                                import is out of scope
//	                                                for the SB3 port)
//	mode=comment&eid=N, POST → 307 /entry/N/comment (body preserved)
//	mode=comment&eid=N, GET  → 301 /entry/N/#comment-form
//	mode=search             → 404
//	(empty / unknown)       → 301 /
//
// 307 preserves the POST body + method so the existing commentSubmit
// handler still owns CSRF / Turnstile / spam checks — this shim only
// smooths out the URL shape.
func (h *Handler) legacyCGI(w http.ResponseWriter, r *http.Request) {
	q := r.URL.Query()
	mode := q.Get("mode")

	// Mode-less external permalinks. SB3's permalink() emits these for
	// dynamic blogs and they're the form most likely to live in
	// external bookmarks / search indexes.
	if mode == "" {
		if eid := q.Get("eid"); eid != "" {
			h.redirectLegacyEntryID(w, r, eid)
			return
		}
		if cid := q.Get("cid"); cid != "" {
			h.redirectLegacyCategoryID(w, r, cid)
			return
		}
		if m := q.Get("month"); m != "" {
			redirectLegacyMonth(w, r, m)
			return
		}
		http.Redirect(w, r, "/", http.StatusMovedPermanently)
		return
	}

	switch mode {
	case "entry":
		if eid := q.Get("eid"); eid != "" {
			h.redirectLegacyEntryID(w, r, eid)
			return
		}
		http.Redirect(w, r, "/", http.StatusMovedPermanently)
	case "category":
		if cid := q.Get("cid"); cid != "" {
			h.redirectLegacyCategoryID(w, r, cid)
			return
		}
		http.NotFound(w, r)
	case "archive":
		cond := q.Get("cond")
		if len(cond) == 4 {
			http.Redirect(w, r, "/archive/"+cond+"/", http.StatusMovedPermanently)
			return
		}
		if len(cond) == 6 {
			http.Redirect(w, r, "/archive/"+cond[:4]+"/"+cond[4:]+"/", http.StatusMovedPermanently)
			return
		}
		http.NotFound(w, r)
	case "user":
		// User import is out of scope (SB3 stored crypt() hashes
		// incompatible with bcrypt) so SB3 user_id == Go user.id is
		// never guaranteed. We honour the existing pid passthrough
		// rather than 404 to keep imported templates that emit
		// {site_cgi}?mode=user&pid=N pointing somewhere useful.
		if pid := q.Get("pid"); pid != "" {
			http.Redirect(w, r, "/profile/"+pid+"/", http.StatusMovedPermanently)
			return
		}
		http.NotFound(w, r)
	case "comment":
		eid := q.Get("eid")
		if eid == "" {
			http.NotFound(w, r)
			return
		}
		// Comment submission: forward to the canonical entry id. We
		// keep this as id-passthrough rather than legacy_id lookup
		// because the URL is generated by an imported template and
		// goes away once that template is replaced; the rare
		// post-import comment hit is acceptable collateral.
		if r.Method == http.MethodPost {
			http.Redirect(w, r, "/entry/"+eid+"/comment", http.StatusTemporaryRedirect)
			return
		}
		http.Redirect(w, r, "/entry/"+eid+"/#comment-form", http.StatusMovedPermanently)
	case "search":
		// Search isn't implemented yet. 404 surfaces the gap rather
		// than silently redirecting to an empty home — once a /search
		// route lands this branch becomes a 301 forwarder.
		http.NotFound(w, r)
	case "page":
		http.Redirect(w, r, "/", http.StatusMovedPermanently)
	default:
		// Unknown mode values (mobile, rsd, trackback…) land on the
		// home page rather than 404 so a misconfigured imported
		// template doesn't drop the reader off a cliff.
		_ = strings.TrimSpace(mode)
		http.Redirect(w, r, "/", http.StatusMovedPermanently)
	}
}

func (h *Handler) redirectLegacyEntryID(w http.ResponseWriter, r *http.Request, eid string) {
	legacyID, err := strconv.ParseInt(eid, 10, 64)
	if err != nil {
		http.NotFound(w, r)
		return
	}
	ref, err := h.Store.EntryByLegacyID(r.Context(), h.WID, legacyID)
	if err != nil {
		if errors.Is(err, repo.ErrNotFound) {
			http.NotFound(w, r)
			return
		}
		http.Error(w, "lookup failed", http.StatusInternalServerError)
		return
	}
	http.Redirect(w, r, "/entry/"+entryKeyForRef(ref)+"/", http.StatusMovedPermanently)
}

func (h *Handler) redirectLegacyCategoryID(w http.ResponseWriter, r *http.Request, cid string) {
	legacyID, err := strconv.ParseInt(cid, 10, 64)
	if err != nil {
		http.NotFound(w, r)
		return
	}
	id, err := h.Store.CategoryIDByLegacyID(r.Context(), h.WID, legacyID)
	if err != nil {
		if errors.Is(err, repo.ErrNotFound) {
			http.NotFound(w, r)
			return
		}
		http.Error(w, "lookup failed", http.StatusInternalServerError)
		return
	}
	http.Redirect(w, r, "/category/"+strconv.FormatInt(id, 10)+"/", http.StatusMovedPermanently)
}

// redirectLegacyMonth handles ?month=YYYYMM. The Go archive route is
// /archive/YYYY/MM/, so we just split + redirect — no DB lookup needed.
// Bad shapes 404 rather than guess.
func redirectLegacyMonth(w http.ResponseWriter, r *http.Request, m string) {
	if len(m) != 6 {
		http.NotFound(w, r)
		return
	}
	if _, err := strconv.Atoi(m); err != nil {
		http.NotFound(w, r)
		return
	}
	http.Redirect(w, r, "/archive/"+m[:4]+"/"+m[4:]+"/", http.StatusMovedPermanently)
}

// entryKeyForRef mirrors entryKeyFor() but takes the redirect-only
// repo.LegacyEntryRef so we don't have to load the full domain.Entry
// just to pick between slug and id.
func entryKeyForRef(ref repo.LegacyEntryRef) string {
	if ref.Slug != "" {
		return ref.Slug
	}
	return strconv.FormatInt(ref.ID, 10)
}
